### ISSUE TITLE
Adding new items on the fly for TagSelector

### ISSUE THREAD

**Issue by xadagaras** [mwinkler/Blazor.Components#1]
Hi,

first of all, I like this component so far. The only thing that I would like to be able is that the user could add new items to the TagSelector component instead of just selecting existing ones.

For example the list contains on load the following items:
* Item 1
* Item 2
* Item 3
* Item 4
* Item 5
* Item 6

User enters Item 7 and presses either "Enter" or "," then this should be added to the list and be selected.

Regards

Daniel

**Comment by mwinkler** [comment]
Hi
Thank you for your feedback.
I could add a new event, gets fired if the entered value was found in the given data items.

**Comment by mwinkler** [comment]
Add new EventCallback "OnCreateTag" in version 1.2
Sorry for the delay...
