### ISSUE TITLE
Fontawesome

### ISSUE THREAD

**Issue by bgriffy** [mwinkler/Blazor.Components#11]
Is the tree component dependent on Fontawesome? 

I am trying to use the tree component and have copied the demo code exactly, but the icons to expand the nodes are not there. 

If the package is dependant on font-awesome, it might be a good idea to add that info to the README to save people time. 

Great component btw! Super hard to find one of these for free.

**Comment by mwinkler** [comment]
Hi
Yes, your absolutely right, I will add a notice or maybe remove the dependency.
Thank you.

**Comment by bgriffy** [comment]
Sounds good, thanks for the reply!
