### ISSUE TITLE
HTML not working

### ISSUE THREAD

**Issue by AnniSmiles** [mwinkler/Blazor.Components#13]
Hello,
I am trying to use your Tree but the HTML doesnt seem to be working. after copy pasting your code and running it this is what im getting. there are no expand-collapse buttons
![image](https://user-images.githubusercontent.com/73358289/158166886-a9bb71d1-6e2c-48bd-a6b6-7f3376685621.png)

**Comment by AnniSmiles** [comment]
The problem is that they are there they just aren't visible. and obviously they dont work either

**Comment by mwinkler** [comment]
Hi, do you have the font awesome icons loaded?
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">`

**Comment by AnniSmiles** [comment]
ah i was missing that one. Thank you.
