### ISSUE TITLE
TreeView is not becomming RTL

### ISSUE THREAD

**Issue by ghost** [mwinkler/Blazor.Components#2]
I use localization without a page refresh, so I use css classes like .myClass-en{} and .myClass-rtlLang{} in one css file: site.css for all the languages, With this TreeView I can't set classes for my RTL language, I wish I could.

**Comment by mwinkler** [comment]
I'm not very familiar with RTL support, but you can override/extend existing css classes (eg. "uic-tree__title") to control the text direction.
You can also override the used css classes by the `Style` property.
If this is not a solution, what do you need to achieve the RTL support?

**Comment by ghost** [comment]
I could overcome this issue by defining separate css files for each language and instead of linking stylesheets in the _Host.cshtml file, define them in MainLayout page, So with this code:
```
`@if (ViewData.UsingMwTree == true)
{
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href=@($"css/mw/{mwStyleSheetName}") rel="stylesheet" />
}`
```
I set the mwStyleSheetName variable based on the selected language for example:
 $"mw.tree-{lang}.css"
