### ISSUE TITLE
SelectedNodeChanged  is used two or more times for this component

### ISSUE THREAD

**Issue by ghost** [mwinkler/Blazor.Components#4]
This is a part of markup I use to set up the Tree:

```
`<MW.Blazor.Tree Nodes="Items"  SelectedNodeChanged="@((item) => NodeChanged(item))" ChildSelector="@(item => item.Childs)" @bind-SelectedNode="@selectedNode" 
                @bind-ExpandedNodes="ExpandedNodes" HasChildNodes="@(item => item.Childs?.Any() == true)">`
```
This is the class for TNode:
```
`public class TreeItem
    {
        public int DepartmentID { get; set; }
        public int CategoryID { get; set; }
        public string Text { get; set; }        
        public List<TreeItem> Childs { get; set; }        
    }
`
```
The tree is working fine until I needed to add SelectedNodeChanged to it that I get the error:
SelectedNodeChanged  is used two or more times for this component
when I hover over the red line under the SelectedNodeChanged attribute.
This is the method I want to hook:
```
 IEnumerable<TreeItem> Items = new List<TreeItem>();
 TreeItem selectedNode;
 IList<TreeItem> ExpandedNodes = new List<TreeItem>();

public void NodeChanged(TreeItem item)
    {
        
    }

```
Is this the correct way to attach selectednodechanged to a method?  Or the error is from the tree?

**Comment by IvanJosipovic** [comment]
It seems that we cant use @bind-SelectedNode and SelectedNodeChanged at the same time, as @bind-SelectNode already uses it under the hood.

I solved this issue by adding a  getter/setter to SelectedNode and calling my function in the Setter.

```

<Tree Nodes="Trees" @bind-SelectedNode="SelectedNode" />

    private TreeItem _SelectedNode;

    private TreeItem SelectedNode
    {
        get { return _SelectedNode; }
        set {
            _SelectedNode = value;
            NodeChanged(value);
        }
    }

```
