### ISSUE TITLE
how to subscribe to TreenNode change event?

### ISSUE THREAD

**Issue by gregorvilkner** [mwinkler/Blazor.Components#8]
hi there, could you provide an example of how to subscribe to the SelectedNode change event? i can't figure out how to get this to work.
and thank you, excellent component.
Cheers, Gregor

like this:  
```
@bind-SelectedNode="selectedNode" @bind-SelectedNode:event="selectedNodeChange"
```

with:     
```
Item selectedNode;
private void selectedNodeChange(Item e)    {    }
```

**Comment by mwinkler** [comment]
@gregorvilkner 
You can split the binding to the `@bind-SelectedNode` property in two separate parameter:
```
<Tree Nodes="nodes" SelectedNode="selectedNode" SelectedNodeChanged="(Action<string>)onSelectNode">
    <TitleTemplate>@context</TitleTemplate>
</Tree>

<p style="margin-top: 2rem">
    Selected: @selectedNode
</p>

@code {
    string[] nodes = new[] { "1", "2", "3" };

    string selectedNode;

    void onSelectNode(string node)
    {
        selectedNode = node;
    }
}
```
Regards
Matthias

**Comment by gregorvilkner** [comment]
Danke. This really helps.

In your suggestion, I could do without the binding for SelectedNode="selectedNode" - correct?

I've achieved a similar flow by doing it INotify style with SelectedNode="selectedNode":
~~~
    Item _selectedNode;
    Item selectedNode
    {
        get        {            return _selectedNode;        }
        set        {            _selectedNode=value; other code here...;        }
    {
~~~

My use case includes lazy loading panels with images as the tree is navigated. How can I use "async await" with your suggestion? I've reached good results with turning your "void" into "async void", then using "await", but also incorporating "StateHasChanged();", since the UI won't trigger an update otherwise.

I wonder if there is a way to bind the onNodeChange callback to an Async Task onNodeChangeAsync(TreeNode selectedNode).

Vielen Dank, Gregor

**Comment by mwinkler** [comment]
Hi @gregorvilkner, hier die Async Version:

```
<Tree Nodes="nodes" SelectedNode="selectedNode" SelectedNodeChanged="(Func<string, Task>)onSelectNode">
    <TitleTemplate>@context</TitleTemplate>
</Tree>

<p style="margin-top: 2rem">
    Selected: @selectedNode
</p>

@code {
    string[] nodes = new[] { "1", "2", "3" };

    string selectedNode;

    async Task onSelectNode(string node)
    {
        selectedNode = node;
    }
}
```
Viele Grüsse
Matthias

**Comment by gregorvilkner** [comment]
Awesome. I'll give this a try. Thanks so much. Cheers, Gregor
I think I'm mostly struggling with the syntax of those delegates - and you providing a sample is just wonderful. Haven't seen Func<string,Task> in this context before. I think I was expecting an EventCallback... Liebe Grüße.
make sure to check episode 4 "this is war" of netflix's "high score" - it's all about your fun little avatar. :)
